import testImg from '../assets/testImg.png'
import { type Book, type BooksCatalog, EXCHANGE_METHOD, EXCHANGE_TYPE, PLACES } from './models'

export const BOOK_MOCKS: BooksCatalog['items'] = [
  {
    id: 1,
    name: 'Мастер и Маргарита',
    author: 'Михаил Булгаков',
    place: 'MY_PLACE',
    exchangeType: 'EXCHANGE',
    exchangeMethod: 'MEETING',
    isFavorite: true,
  },
  {
    id: 2,
    name: 'Преступление и наказание',
    author: 'Фёдор Достоевский',
    place: 'NEAR',
    exchangeType: 'FREE',
    exchangeMethod: 'DELIVERY',
    isFavorite: false,
  },
  {
    id: 3,
    name: 'Война и мир',
    author: 'Лев Толстой',
    place: 'RUSSIA',
    exchangeType: 'EXCHANGE',
    exchangeMethod: 'ALL',
    isFavorite: true,
  },
  {
    id: 4,
    name: 'Анна Каренина',
    author: 'Лев Толстой',
    place: 'MY_PLACE',
    exchangeType: 'FREE',
    exchangeMethod: 'MEETING',
    isFavorite: false,
  },
  {
    id: 5,
    name: 'Евгений Онегин',
    author: 'Александр Пушкин',
    place: 'NEAR',
    exchangeType: 'EXCHANGE',
    exchangeMethod: 'DELIVERY',
    isFavorite: true,
  },
  {
    id: 6,
    name: 'Мёртвые души',
    author: 'Николай Гоголь',
    place: 'RUSSIA',
    exchangeType: 'EXCHANGE',
    exchangeMethod: 'ALL',
    isFavorite: false,
  },
  {
    id: 7,
    name: 'Тихий Дон',
    author: 'Михаил Шолохов',
    place: 'MY_PLACE',
    exchangeType: 'FREE',
    exchangeMethod: 'MEETING',
    isFavorite: true,
  },
  {
    id: 8,
    name: 'Доктор Живаго',
    author: 'Борис Пастернак',
    place: 'NEAR',
    exchangeType: 'EXCHANGE',
    exchangeMethod: 'DELIVERY',
    isFavorite: false,
  },
  {
    id: 9,
    name: 'Собачье сердце',
    author: 'Михаил Булгаков',
    place: 'RUSSIA',
    exchangeType: 'FREE',
    exchangeMethod: 'ALL',
    isFavorite: true,
  },
  {
    id: 10,
    name: '451 градус по Фаренгейту',
    author: 'Рэй Брэдбери',
    place: 'MY_PLACE',
    exchangeType: 'EXCHANGE',
    exchangeMethod: 'MEETING',
    isFavorite: false,
  },
]

export const BOOKPAGEMOCK: Book = {
  exchangeType: 'EXCHANGE',
  exchangeMethod: 'ALL',
  name: 'Мастер и Маргарита',
  author: 'Михаил Булгаков',
  condition: 'EXCELLENT',
  defects: 'Незначительные потертости на обложке',
  genre: 'Роман',
  cover: 'HARDCOVER',
  isFavorite: true,
  publisherHouse: 'Азбука',
  year: 2020,
  series: 'Классика XX века',
  description: 'Роман "Мастер и Маргарита" - самое известное произведение Михаила Булгакова...',
  registrationDate: '2024-01-15',
  obtainingMethod: 'Самовывоз',
  otherBooks: [
    {
      id: 1,
      name: 'Собачье сердце',
      author: 'Михаил Булгаков',
      place: 'MY_PLACE',
      src: testImg,
      exchangeType: 'EXCHANGE',
      exchangeMethod: 'MEETING',
      isFavorite: false,
    },
    {
      id: 2,
      name: 'Белая гвардия',
      author: 'Михаил Булгаков',
      place: 'NEAR',
      src: testImg,
      exchangeType: 'FREE',
      exchangeMethod: 'DELIVERY',
      isFavorite: true,
    },
    {
      id: 3,
      name: 'Роковые яйца',
      author: 'Михаил Булгаков',
      place: 'RUSSIA',
      src: testImg,
      exchangeType: 'EXCHANGE',
      exchangeMethod: 'ALL',
      isFavorite: false,
    },
  ],
  userInfo: {
    shortName: 'Анна',
    city: 'Москва',
    isMy: true,
    name: 'Анна Иванова',
    avatar: testImg,
    userId: 'user_123456',
    raiting: '4.8',
    feedbacksNumbe: 127,
    registrationDate: '2023-06-10',
  },

  photos: [
    { url: testImg, isMain: true },
    { url: 'https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg', isMain: false },
    { url: testImg, isMain: false },
    { url: testImg, isMain: false },
  ],
}
